# Generated by Django 3.2.11 on 2022-05-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('B.Tech', 'B.Tech'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('M.Tech', 'M.Tech')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=10),
        ),
    ]
